using ScienceActivityRecorder.Models;
using System.Collections.Generic;
using System.Linq;

namespace ScienceActivityRecorder.Providers
{
    public class OrganizationProvider
    {
        private static List<Organization> _predefinedOrganizations = new List<Organization>();

        static OrganizationProvider()
        {
            _predefinedOrganizations.Add(new Organization(string.Empty));
            _predefinedOrganizations.Add(new Organization("Академія муніципального управління"));
            _predefinedOrganizations.Add(new Organization("Академія праці, соціальних відносин і туризму"));
            _predefinedOrganizations.Add(new Organization("Академія рекреаційних технологій і права"));
            _predefinedOrganizations.Add(new Organization("Академія фінансового управління"));
            _predefinedOrganizations.Add(new Organization("Апарат Президії НАН України"));
            _predefinedOrganizations.Add(new Organization("Бердянський державний педагогічний університет"));
            _predefinedOrganizations.Add(new Organization("Бердянський університет менеджменту і бізнесу"));
            _predefinedOrganizations.Add(new Organization("Білоцерківський національний аграрний університет"));
            _predefinedOrganizations.Add(new Organization("Біосферний заповідник \"Асканія-Нова\" ім.Ф.Е.Фальц-Фейна"));
            _predefinedOrganizations.Add(new Organization("Буковинський державний медичний університет"));
            _predefinedOrganizations.Add(new Organization("Буковинський університет"));
            _predefinedOrganizations.Add(new Organization("Вінницький державний педагогічний університет імені Михайла Коцюбинського"));
            _predefinedOrganizations.Add(new Organization("Вінницький кооперативний інститут"));
            _predefinedOrganizations.Add(new Organization("Вінницький національний аграрний університет"));
            _predefinedOrganizations.Add(new Organization("Вінницький національний медичний університет ім.М.І.Пирогова"));
            _predefinedOrganizations.Add(new Organization("Вінницький національний технічний університет"));
            _predefinedOrganizations.Add(new Organization("Глухівський національний педагогічний університет імені Олександра Довженка"));
            _predefinedOrganizations.Add(new Organization("Головна астрономічна обсерваторія"));
            _predefinedOrganizations.Add(new Organization("Державна дослідна станція птахівництва"));
            _predefinedOrganizations.Add(new Organization("Державна екологічна академія післядипломної освіти та управління"));
            _predefinedOrganizations.Add(new Organization("Державна науково-педагогічна бібліотека України ім.В.О.Сухомлинського"));
            _predefinedOrganizations.Add(new Organization("Державний економіко-технологічний університет транспорту"));
            _predefinedOrganizations.Add(new Organization("Державний природознавчий музей"));
            _predefinedOrganizations.Add(new Organization("Державний університет телекомунікацій"));
            _predefinedOrganizations.Add(new Organization("Дипломатична академія України"));
            _predefinedOrganizations.Add(new Organization("Дніпропетровська медична академія"));
            _predefinedOrganizations.Add(new Organization("Дніпропетровський державний аграрно-економічний університет"));
            _predefinedOrganizations.Add(new Organization("Дніпропетровський національний університет залізничного транспорту імені академіка В.Лазаряна"));
            _predefinedOrganizations.Add(new Organization("Дніпропетровський національний університет імені Олеся Гончара"));
            _predefinedOrganizations.Add(new Organization("Дніпропетровський регіональний інститут державного управління Національної академії державного управління при Президентові України"));
            _predefinedOrganizations.Add(new Organization("Дніпропетровський університет імені Альфреда Нобеля"));
            _predefinedOrganizations.Add(new Organization("Донбаська державна машинобудівна академія"));
            _predefinedOrganizations.Add(new Organization("Донбаський державний педагогічний університет"));
            _predefinedOrganizations.Add(new Organization("Донецька академія автомобільного транспорту"));
            _predefinedOrganizations.Add(new Organization("Донецький національний медичний університет імені Максима Горького"));
            _predefinedOrganizations.Add(new Organization("Донецький національний технічний університет"));
            _predefinedOrganizations.Add(new Organization("Донецький національний університет"));
            _predefinedOrganizations.Add(new Organization("Донецький національний університет економіки і торгівлі імені Михайла Туган-Барановського"));
            _predefinedOrganizations.Add(new Organization("Донецький фізико-технічний інститут ім.О.О.Галкіна"));
            _predefinedOrganizations.Add(new Organization("Дрогобицький державний педагогічний університет імені Івана Франка"));
            _predefinedOrganizations.Add(new Organization("Європейський університет"));
            _predefinedOrganizations.Add(new Organization("Житомирський військовий інститут ім.С.П.Корольова Державного університету телекомунікацій"));
            _predefinedOrganizations.Add(new Organization("Житомирський державний технологічний університет"));
            _predefinedOrganizations.Add(new Organization("Житомирський державний університет імені Івана Франка"));
            _predefinedOrganizations.Add(new Organization("Житомирський національний агроекологічний університет"));
            _predefinedOrganizations.Add(new Organization("Житомирський обласний інститут післядипломної педагогічної освіти"));
            _predefinedOrganizations.Add(new Organization("Закарпатська державна сільськогосподарська дослідна станція"));
            _predefinedOrganizations.Add(new Organization("Запорізька державна інженерна академія"));
            _predefinedOrganizations.Add(new Organization("Запорізька медична академія післядипломної освіти"));
            _predefinedOrganizations.Add(new Organization("Запорізький державний медичний університет"));
            _predefinedOrganizations.Add(new Organization("Запорізький національний технічний університет"));
            _predefinedOrganizations.Add(new Organization("Запорізький національний університет"));
            _predefinedOrganizations.Add(new Organization("Івано-Франківський національний технічний університет нафти і газу"));
            _predefinedOrganizations.Add(new Organization("Івано-Франківський університет права імені Короля Данила Галицького"));
            _predefinedOrganizations.Add(new Organization("Інститут аграрної економіки"));
            _predefinedOrganizations.Add(new Organization("Інститут агроекології і природокористування"));
            _predefinedOrganizations.Add(new Organization("Інститут археології"));
            _predefinedOrganizations.Add(new Organization("Інститут бджільництва ім.П.І.Прокоповича"));
            _predefinedOrganizations.Add(new Organization("Інститут біоенергетичних культур і цукрових буряків"));
            _predefinedOrganizations.Add(new Organization("Інститут біоколоїдної хімії ім.Ф.Д.Овчаренка"));
            _predefinedOrganizations.Add(new Organization("Інститут біології клітини"));
            _predefinedOrganizations.Add(new Organization("Інститут біології південних морів ім.О.О.Ковалевського"));
            _predefinedOrganizations.Add(new Organization("Інститут біології тварин"));
            _predefinedOrganizations.Add(new Organization("Інститут біоорганічної хімії та нафтохімії"));
            _predefinedOrganizations.Add(new Organization("Інститут біохімії ім.О.В.Палладіна"));
            _predefinedOrganizations.Add(new Organization("Інститут ботаніки ім.М.Г.Холодного"));
            _predefinedOrganizations.Add(new Organization("Інститут виноградарства і виноробства ім.В.Є.Таїрова"));
            _predefinedOrganizations.Add(new Organization("Інститут вищої освіти"));
            _predefinedOrganizations.Add(new Organization("Інститут водних проблем і меліорації"));
            _predefinedOrganizations.Add(new Organization("Інститут всесвітньої історії"));
            _predefinedOrganizations.Add(new Organization("Інститут газу"));
            _predefinedOrganizations.Add(new Organization("Інститут генетичної та регенеративної медицини"));
            _predefinedOrganizations.Add(new Organization("Інститут геологічних наук"));
            _predefinedOrganizations.Add(new Organization("Інститут геотехнічної механіки ім.М.С.Полякова"));
            _predefinedOrganizations.Add(new Organization("Інститут геофізики ім.С.І.Субботіна"));
            _predefinedOrganizations.Add(new Organization("Інститут геохімії навколишнього середовища"));
            _predefinedOrganizations.Add(new Organization("Інститут геронтології ім.Д.Ф.Чеботарьова"));
            _predefinedOrganizations.Add(new Organization("Інститут гідробіології"));
            _predefinedOrganizations.Add(new Organization("Інститут гідромеханіки"));
            _predefinedOrganizations.Add(new Organization("Інститут громадського здоров’я імені О.М.Марзєєва"));
            _predefinedOrganizations.Add(new Organization("Інститут грунтознавства та агрохімії ім.О.Н.Соколовського"));
            _predefinedOrganizations.Add(new Organization("Інститут демографії та соціальних досліджень ім.М.В.Птухи"));
            _predefinedOrganizations.Add(new Organization("Інститут держави і права ім.В.М.Корецького"));
            _predefinedOrganizations.Add(new Organization("Інститут досліджень науково-технічного потенціалу та історії науки ім.Г.М.Доброва"));
            _predefinedOrganizations.Add(new Organization("Інститут еволюційної екології"));
            _predefinedOrganizations.Add(new Organization("Інститут економіки природокористування та сталого розвитку"));
            _predefinedOrganizations.Add(new Organization("Інститут економіки промисловості"));
            _predefinedOrganizations.Add(new Organization("Інститут економіки та прогнозування"));
            _predefinedOrganizations.Add(new Organization("Інститут економіко-правових досліджень"));
            _predefinedOrganizations.Add(new Organization("Інститут експериментальної і клінічної ветеринарної медицини"));
            _predefinedOrganizations.Add(new Organization("Інститут експериментальної патології&#44; онкології і радіобіології ім.Р.Є.Кавецького"));
            _predefinedOrganizations.Add(new Organization("Інститут електродинаміки"));
            _predefinedOrganizations.Add(new Organization("Інститут електрозварювання ім.Є.О.Патона"));
            _predefinedOrganizations.Add(new Organization("Інститут електронної фізики"));
            _predefinedOrganizations.Add(new Organization("Інститут ендокринології та обміну речовин ім.В.П.Комісаренка"));
            _predefinedOrganizations.Add(new Organization("Інститут загальної та неорганічної хімії ім.В.І.Вернадського"));
            _predefinedOrganizations.Add(new Organization("Інститут захисту рослин"));
            _predefinedOrganizations.Add(new Organization("Інститут землеробства"));
            _predefinedOrganizations.Add(new Organization("Інститут зоології ім.І.І.Шмальгаузена"));
            _predefinedOrganizations.Add(new Organization("Інститут зрошуваного землеробства"));
            _predefinedOrganizations.Add(new Organization("Інститут імпульсних процесів і технологій"));
            _predefinedOrganizations.Add(new Organization("Інститут інформаційних технологій і засобів навчання"));
            _predefinedOrganizations.Add(new Organization("Інститут іоносфери"));
            _predefinedOrganizations.Add(new Organization("Інститут історії України"));
            _predefinedOrganizations.Add(new Organization("Інститут кардіології імені академіка М.Д.Стражеска"));
            _predefinedOrganizations.Add(new Organization("Інститут кібернетики ім.В.М.Глушкова"));
            _predefinedOrganizations.Add(new Organization("Інститут клітинної біології та генетичної інженерії"));
            _predefinedOrganizations.Add(new Organization("Інститут кормів та сільського господарства Поділля"));
            _predefinedOrganizations.Add(new Organization("Інститут космічних досліджень"));
            _predefinedOrganizations.Add(new Organization("Інститут культурології"));
            _predefinedOrganizations.Add(new Organization("Інститут літератури ім.Т.Г.Шевченка"));
            _predefinedOrganizations.Add(new Organization("Інститут магнетизму"));
            _predefinedOrganizations.Add(new Organization("Інститут математики"));
            _predefinedOrganizations.Add(new Organization("Інститут медицини праці"));
            _predefinedOrganizations.Add(new Organization("Інститут металофізики ім.Г.В.Курдюмова"));
            _predefinedOrganizations.Add(new Organization("Інститут механізації та електрифікації сільського господарства"));
            _predefinedOrganizations.Add(new Organization("Інститут механіки ім.С.П.Тимошенка"));
            _predefinedOrganizations.Add(new Organization("Інститут мікробіології і вірусології ім.Д.К.Заболотного"));
            _predefinedOrganizations.Add(new Organization("Інститут мовознавства ім.О.О.Потебні"));
            _predefinedOrganizations.Add(new Organization("Інститут молекулярної біології і генетики"));
            _predefinedOrganizations.Add(new Organization("Інститут монокристалів"));
            _predefinedOrganizations.Add(new Organization("Інститут морської біології"));
            _predefinedOrganizations.Add(new Organization("Інститут надтвердих матеріалів ім.В.М.Бакуля"));
            _predefinedOrganizations.Add(new Organization("Інститут нейрохірургії ім.акад.А.П.Ромоданова"));
            _predefinedOrganizations.Add(new Organization("Інститут овочівництва і баштанництва"));
            _predefinedOrganizations.Add(new Organization("Інститут олійних культур"));
            _predefinedOrganizations.Add(new Organization("Інститут органічної хімії"));
            _predefinedOrganizations.Add(new Organization("Інститут патології хребта та суглобів імені проф.&nbsp;М.І.Ситенка"));
            _predefinedOrganizations.Add(new Organization("Інститут педагогіки"));
            _predefinedOrganizations.Add(new Organization("Інститут педагогічної освіти і освіти дорослих"));
            _predefinedOrganizations.Add(new Organization("Інститут педіатрії акушерства і гінекології"));
            _predefinedOrganizations.Add(new Organization("Інститут підготовки кадрів Державної служби зайнятості України"));
            _predefinedOrganizations.Add(new Organization("Інститут політичних і етнонаціональних досліджень ім.І.Ф.Кураса"));
            _predefinedOrganizations.Add(new Organization("Інститут прикладних проблем механіки і математики ім.Я.С.Підстригача"));
            _predefinedOrganizations.Add(new Organization("Інститут прикладної математики і механіки"));
            _predefinedOrganizations.Add(new Organization("Інститут прикладної фізики"));
            _predefinedOrganizations.Add(new Organization("Інститут проблем виховання"));
            _predefinedOrganizations.Add(new Organization("Інститут проблем ендокринної патології ім.В.Я.Данилевського"));
            _predefinedOrganizations.Add(new Organization("Інститут проблем кріобіології і кріомедицини"));
            _predefinedOrganizations.Add(new Organization("Інститут проблем математичних машин та систем"));
            _predefinedOrganizations.Add(new Organization("Інститут проблем матеріалознавства ім.І.М.Францевича"));
            _predefinedOrganizations.Add(new Organization("Інститут проблем машинобудування ім.А.М.Підгорного"));
            _predefinedOrganizations.Add(new Organization("Інститут проблем міцності ім.Г.С.Писаренка"));
            _predefinedOrganizations.Add(new Organization("Інститут проблем моделювання в енергетиці ім.Г.Є.Пухова"));
            _predefinedOrganizations.Add(new Organization("Інститут проблем реєстрації інформації"));
            _predefinedOrganizations.Add(new Organization("Інститут проблем ринку та економіко-екологічних досліджень"));
            _predefinedOrganizations.Add(new Organization("Інститут проблем штучного інтелекту"));
            _predefinedOrganizations.Add(new Organization("Інститут програмних систем"));
            _predefinedOrganizations.Add(new Organization("Інститут продовольчих ресурсів"));
            _predefinedOrganizations.Add(new Organization("Інститут професійно-технічної освіти"));
            _predefinedOrganizations.Add(new Organization("Інститут психології ім.Г.С.Костюка"));
            _predefinedOrganizations.Add(new Organization("Інститут радіофізики та електроніки ім.О.Я.Усикова"));
            _predefinedOrganizations.Add(new Organization("Інститут регіональних досліджень ім.М.І.Долішнього"));
            _predefinedOrganizations.Add(new Organization("Інститут рибного господарства"));
            _predefinedOrganizations.Add(new Organization("Інститут рибного господарства - Львівська дослідна станція"));
            _predefinedOrganizations.Add(new Organization("Інститут рису"));
            _predefinedOrganizations.Add(new Organization("Інститут розведення і генетики тварин ім.М.В.Зубця"));
            _predefinedOrganizations.Add(new Organization("Інститут рослинництва ім.В.Я.Юр’єва"));
            _predefinedOrganizations.Add(new Organization("Інститут садівництва"));
            _predefinedOrganizations.Add(new Organization("Інститут сільського господарства Карпатського регіону"));
            _predefinedOrganizations.Add(new Organization("Інститут сільського господарства Полісся"));
            _predefinedOrganizations.Add(new Organization("Інститут сільського господарства степової зони"));
            _predefinedOrganizations.Add(new Organization("Інститут сільськогосподарської мікробіології та агропромислового виробництва"));
            _predefinedOrganizations.Add(new Organization("Інститут соціальної та політичної психології"));
            _predefinedOrganizations.Add(new Organization("Інститут соціології"));
            _predefinedOrganizations.Add(new Organization("Інститут спеціальної педагогіки"));
            _predefinedOrganizations.Add(new Organization("Інститут сходознавства ім.А.Ю.Кримського"));
            _predefinedOrganizations.Add(new Organization("Інститут сцинтиляційних матеріалів"));
            _predefinedOrganizations.Add(new Organization("Інститут тваринництва"));
            _predefinedOrganizations.Add(new Organization("Інститут тваринництва степових районів ім.М.Ф.Іванова «Асканія-Нова»"));
            _predefinedOrganizations.Add(new Organization("Інститут телекомунікацій і глобального інформаційного простору"));
            _predefinedOrganizations.Add(new Organization("Інститут теоретичної фізики ім.М.М.Боголюбова"));
            _predefinedOrganizations.Add(new Organization("Інститут технічних проблем магнетизму"));
            _predefinedOrganizations.Add(new Organization("Інститут технічної теплофізики"));
            _predefinedOrganizations.Add(new Organization("Інститут українознавства імені Івана Крип’якевича"));
            _predefinedOrganizations.Add(new Organization("Інститут української мови"));
            _predefinedOrganizations.Add(new Organization("Інститут урології"));
            _predefinedOrganizations.Add(new Organization("Інститут фізики"));
            _predefinedOrganizations.Add(new Organization("Інститут фізики конденсованих систем"));
            _predefinedOrganizations.Add(new Organization("Інститут фізики напівпровідників ім.В.Є.Лашкарьова"));
            _predefinedOrganizations.Add(new Organization("Інститут фізичної оптики ім.О.Г.Влоха"));
            _predefinedOrganizations.Add(new Organization("Інститут фізичної хімії ім.Л.В.Писаржевського"));
            _predefinedOrganizations.Add(new Organization("Інститут фізіології ім.О.О.Богомольця"));
            _predefinedOrganizations.Add(new Organization("Інститут фізіології рослин і генетики"));
            _predefinedOrganizations.Add(new Organization("Інститут філософії ім.Г.С.Сковороди"));
            _predefinedOrganizations.Add(new Organization("Інститут харчової біотехнології та геноміки"));
            _predefinedOrganizations.Add(new Organization("Інститут хімії високомолекулярних сполук"));
            _predefinedOrganizations.Add(new Organization("Інститут хімії поверхні ім.О.О.Чуйка"));
            _predefinedOrganizations.Add(new Organization("Інститут чорної металургії ім.З.І.Некрасова"));
            _predefinedOrganizations.Add(new Organization("Інститут ядерних досліджень"));
            _predefinedOrganizations.Add(new Organization("Кам’янець-Подільський національний університет імені Івана Огієнка"));
            _predefinedOrganizations.Add(new Organization("Київська школа економіки"));
            _predefinedOrganizations.Add(new Organization("Київський національний економічний університет імені Вадима Гетьмана"));
            _predefinedOrganizations.Add(new Organization("Київський національний лінгвістичний університет"));
            _predefinedOrganizations.Add(new Organization("Київський національний торговельно-економічний університет"));
            _predefinedOrganizations.Add(new Organization("Київський національний університет будівництва і архітектури"));
            _predefinedOrganizations.Add(new Organization("Київський національний університет імені Тараса Шевченка"));
            _predefinedOrganizations.Add(new Organization("Київський національний університет культури і мистецтв"));
            _predefinedOrganizations.Add(new Organization("Київський національний університет технологій та дизайну"));
            _predefinedOrganizations.Add(new Organization("Київський університет імені Бориса Грінченка"));
            _predefinedOrganizations.Add(new Organization("Кіровоградська державна сільськогосподарська дослідна станція"));
            _predefinedOrganizations.Add(new Organization("Кіровоградський національний технічний університет"));
            _predefinedOrganizations.Add(new Organization("Класичний приватний університет"));
            _predefinedOrganizations.Add(new Organization("Кременчуцький національний університет імені Михайла Остроградського"));
            _predefinedOrganizations.Add(new Organization("Криворізький державний педагогічний університет"));
            _predefinedOrganizations.Add(new Organization("Криворізький національний університет"));
            _predefinedOrganizations.Add(new Organization("Кримська астрофізична обсерваторія"));
            _predefinedOrganizations.Add(new Organization("Кримський державний медичний університет ім.С.І.Георгієвського"));
            _predefinedOrganizations.Add(new Organization("Луганський державний медичний університет"));
            _predefinedOrganizations.Add(new Organization("Луганський національний університет імені Тараса Шевченка"));
            _predefinedOrganizations.Add(new Organization("Луцький національний технічний університет"));
            _predefinedOrganizations.Add(new Organization("Львівський державний університет безпеки життєдіяльності"));
            _predefinedOrganizations.Add(new Organization("Львівський державний університет внутрішніх справ"));
            _predefinedOrganizations.Add(new Organization("Львівський державний університет фізичної культури"));
            _predefinedOrganizations.Add(new Organization("Львівський інститут економіки і туризму"));
            _predefinedOrganizations.Add(new Organization("Львівський науково-практичний центр професійно-технічної освіти"));
            _predefinedOrganizations.Add(new Organization("Львівський національний аграрний університет"));
            _predefinedOrganizations.Add(new Organization("Львівський національний медичний університет імені Данила Галицького"));
            _predefinedOrganizations.Add(new Organization("Львівський національний університет ветеринарної медицини та біотехнологій ім.С.З.Гжицького"));
            _predefinedOrganizations.Add(new Organization("Львівський національний університет імені Івана Франка"));
            _predefinedOrganizations.Add(new Organization("Львівський торговельно-економічний університет"));
            _predefinedOrganizations.Add(new Organization("Маріупольський державний університет"));
            _predefinedOrganizations.Add(new Organization("Мелітопольський державний педагогічний університет імені Богдана Хмельницького"));
            _predefinedOrganizations.Add(new Organization("Миколаївський національний аграрний університет"));
            _predefinedOrganizations.Add(new Organization("Миколаївський національний університет ім.В.О.Сухомлинського"));
            _predefinedOrganizations.Add(new Organization("Міжнародна клініка відновного лікування"));
            _predefinedOrganizations.Add(new Organization("Міжнародний гуманітарний університет"));
            _predefinedOrganizations.Add(new Organization("Міжнародний інститут соціоніки"));
            _predefinedOrganizations.Add(new Organization("Міжнародний науково-навчальний центр інформаційних технологій і систем"));
            _predefinedOrganizations.Add(new Organization("Міжрегіональна Академія управління персоналом"));
            _predefinedOrganizations.Add(new Organization("Морський гідрофізичний інститут"));
            _predefinedOrganizations.Add(new Organization("Мукачівський державний університет"));
            _predefinedOrganizations.Add(new Organization("Навчально-науковий професійно-педагогічний інститут Української інженерно-педагогічної академії"));
            _predefinedOrganizations.Add(new Organization("Науково-дослідний інститут вивчення проблем злочинності імені академіка В.В.Сташиса"));
            _predefinedOrganizations.Add(new Organization("Науково-дослідний інститут державного будівництва та місцевого самоврядування"));
            _predefinedOrganizations.Add(new Organization("Науково-дослідний інститут інтелектуальної власності"));
            _predefinedOrganizations.Add(new Organization("Науково-дослідний інститут інформатики і права"));
            _predefinedOrganizations.Add(new Organization("Науково-дослідний інститут правового забезпечення інноваційного розвитку"));
            _predefinedOrganizations.Add(new Organization("Науково-дослідний інститут приватного права і підприємництва імені академіка Ф.Г.Бурчака"));
            _predefinedOrganizations.Add(new Organization("Науково-дослідний інститут українознавства"));
            _predefinedOrganizations.Add(new Organization("Науково-дослідний центр індустріальних проблем розвитку"));
            _predefinedOrganizations.Add(new Organization("Науково-практичний медичний центр дитячої кардіології та кардіохірургії"));
            _predefinedOrganizations.Add(new Organization("Науково-практичний центр ендоваскулярної нейрорентгенохірургії"));
            _predefinedOrganizations.Add(new Organization("Національна академія державного управління при Президентові України"));
            _predefinedOrganizations.Add(new Organization("Національна академія Державної прикордонної служби України імені Богдана Хмельницького"));
            _predefinedOrganizations.Add(new Organization("Національна академія керівних кадрів культури і мистецтв"));
            _predefinedOrganizations.Add(new Organization("Національна академія Національної гвардії України"));
            _predefinedOrganizations.Add(new Organization("Національна академія статистики&#44; обліку та аудиту"));
            _predefinedOrganizations.Add(new Organization("Національна бібліотека України імені В.І.Вернадського"));
            _predefinedOrganizations.Add(new Organization("Національна медична академія післядипломної освіти ім.П.Л.Шупика"));
            _predefinedOrganizations.Add(new Organization("Національна металургійна академія України"));
            _predefinedOrganizations.Add(new Organization("Національна музична академія України імені П.І.Чайковського"));
            _predefinedOrganizations.Add(new Organization("Національна наукова сільськогосподарська бібліотека"));
            _predefinedOrganizations.Add(new Organization("Національний авіаційний університет"));
            _predefinedOrganizations.Add(new Organization("Національний аерокосмічний університет ім.М.Є.Жуковського «Харківський авіаційний інститут»"));
            _predefinedOrganizations.Add(new Organization("Національний ботанічний сад ім.М.М.Гришка"));
            _predefinedOrganizations.Add(new Organization("Національний гірничий університет"));
            _predefinedOrganizations.Add(new Organization("Національний інститут раку"));
            _predefinedOrganizations.Add(new Organization("Національний інститут серцево-судинної хірургії імені М.М.Амосова"));
            _predefinedOrganizations.Add(new Organization("Національний інститут стратегічних досліджень"));
            _predefinedOrganizations.Add(new Organization("Національний інститут терапії імені Л.Т.Малої"));
            _predefinedOrganizations.Add(new Organization("Національний інститут фтизіатрії і пульмонології ім.Ф.Г.Яновського"));
            _predefinedOrganizations.Add(new Organization("Національний лісотехнічний університет України"));
            _predefinedOrganizations.Add(new Organization("Національний медичний університет ім.акад.О.О.Богомольця"));
            _predefinedOrganizations.Add(new Organization("Національний науковий центр радіаційної медицини"));
            _predefinedOrganizations.Add(new Organization("Національний науковий центр «Харківський фізико-технічний інститут»"));
            _predefinedOrganizations.Add(new Organization("Національний науково-природничий музей"));
            _predefinedOrganizations.Add(new Organization("Національний педагогічний університет ім.М.П.Драгоманова"));
            _predefinedOrganizations.Add(new Organization("Національний природний парк «Подільські Товтри»"));
            _predefinedOrganizations.Add(new Organization("Національний технічний університет України «Київський політехнічний інститут імені Ігоря Сікорського»"));
            _predefinedOrganizations.Add(new Organization("Національний технічний університет «Харківський політехнічний інститут»"));
            _predefinedOrganizations.Add(new Organization("Національний транспортний університет"));
            _predefinedOrganizations.Add(new Organization("Національний університет біоресурсів і природокористування України"));
            _predefinedOrganizations.Add(new Organization("Національний університет водного господарства та природокористування"));
            _predefinedOrganizations.Add(new Organization("Національний університет кораблебудування імені адмірала Макарова"));
            _predefinedOrganizations.Add(new Organization("Національний університет оборони України імені Івана Черняховського"));
            _predefinedOrganizations.Add(new Organization("Національний університет фізичного виховання і спорту України"));
            _predefinedOrganizations.Add(new Organization("Національний університет харчових технологій"));
            _predefinedOrganizations.Add(new Organization("Національний університет цивільного захисту України"));
            _predefinedOrganizations.Add(new Organization("Національний університет «Києво-Могилянська академія»"));
            _predefinedOrganizations.Add(new Organization("Національний університет «Львівська політехніка»"));
            _predefinedOrganizations.Add(new Organization("Національний університет «Одеська морська академія»"));
            _predefinedOrganizations.Add(new Organization("Національний університет «Одеська юридична академія»"));
            _predefinedOrganizations.Add(new Organization("Національний університет «Острозька академія»"));
            _predefinedOrganizations.Add(new Organization("Національний фармацевтичний університет"));
            _predefinedOrganizations.Add(new Organization("Національний юридичний університет імені Ярослава Мудрого"));
            _predefinedOrganizations.Add(new Organization("Ніжинський державний університет імені Миколи Гоголя"));
            _predefinedOrganizations.Add(new Organization("Одеська державна академія будівництва та архітектури"));
            _predefinedOrganizations.Add(new Organization("Одеська державна академія технічного регулювання та якості"));
            _predefinedOrganizations.Add(new Organization("Одеська національна академія зв’язку ім.О.С.Попова"));
            _predefinedOrganizations.Add(new Organization("Одеська національна академія харчових технологій"));
            _predefinedOrganizations.Add(new Organization("Одеський державний екологічний університет"));
            _predefinedOrganizations.Add(new Organization("Одеський державний університет внутрішніх справ"));
            _predefinedOrganizations.Add(new Organization("Одеський національний економічний університет"));
            _predefinedOrganizations.Add(new Organization("Одеський національний медичний університет"));
            _predefinedOrganizations.Add(new Organization("Одеський національний морський університет"));
            _predefinedOrganizations.Add(new Organization("Одеський національний політехнічний університет", new List<string> { "Одесский национальный политехнический университет", "Одеський національний політехніний університет" }));
            _predefinedOrganizations.Add(new Organization("Одеський національний університет ім.І.І.Мечникова"));
            _predefinedOrganizations.Add(new Organization("Переяслав-Хмельницький державний педагогічний університет імені Григорія Сковороди"));
            _predefinedOrganizations.Add(new Organization("Південноукраїнський національний педагогічний університет ім.К.Д.Ушинського"));
            _predefinedOrganizations.Add(new Organization("Подільський державний аграрно-технічний університет"));
            _predefinedOrganizations.Add(new Organization("Полтавська державна аграрна академія"));
            _predefinedOrganizations.Add(new Organization("Полтавський національний педагогічний університет ім.В.Г.Короленка"));
            _predefinedOrganizations.Add(new Organization("Полтавський національний технічний університет імені Юрія Кондратюка"));
            _predefinedOrganizations.Add(new Organization("Полтавський обласний інститут післядипломної педагогічної освіти ім.М.В.Остроградського"));
            _predefinedOrganizations.Add(new Organization("Полтавський університет економіки і торгівлі"));
            _predefinedOrganizations.Add(new Organization("Президія Національної академії аграрних наук України"));
            _predefinedOrganizations.Add(new Organization("Президія Національної академії наук України"));
            _predefinedOrganizations.Add(new Organization("Президія Національної академії педагогічних наук України"));
            _predefinedOrganizations.Add(new Organization("Приазовський державний технічний університет"));
            _predefinedOrganizations.Add(new Organization("Придніпровська державна академія будівництва та архітектури"));
            _predefinedOrganizations.Add(new Organization("Придніпровська державна академія фізичної культури і спорту"));
            _predefinedOrganizations.Add(new Organization("Прикарпатський національний університет імені Василя Стефаника"));
            _predefinedOrganizations.Add(new Organization("Радіоастрономічний інститут"));
            _predefinedOrganizations.Add(new Organization("Рівненський державний гуманітарний університет"));
            _predefinedOrganizations.Add(new Organization("Севастопольський державний університет"));
            _predefinedOrganizations.Add(new Organization("Селекційно-генетичний інститут – Національний центр насіннєзнавства та сортовивчення"));
            _predefinedOrganizations.Add(new Organization("Сумський державний педагогічний університет ім.А.С.Макаренка"));
            _predefinedOrganizations.Add(new Organization("Сумський державний університет"));
            _predefinedOrganizations.Add(new Organization("Сумський національний аграрний університет"));
            _predefinedOrganizations.Add(new Organization("Сумський обласний інститут післядипломної педагогічної освіти"));
            _predefinedOrganizations.Add(new Organization("Східноєвропейський національний університет імені Лесі Українки"));
            _predefinedOrganizations.Add(new Organization("Східноукраїнський національний університет імені Володимира Даля"));
            _predefinedOrganizations.Add(new Organization("Таврійський державний агротехнологічний університет"));
            _predefinedOrganizations.Add(new Organization("Таврійський національний університет ім.В.І.Вернадського"));
            _predefinedOrganizations.Add(new Organization("Тернопільський державний медичний університет ім.І.Я.Горбачевського"));
            _predefinedOrganizations.Add(new Organization("Тернопільський національний економічний університет"));
            _predefinedOrganizations.Add(new Organization("Тернопільський національний педагогічний університет імені Володимира Гнатюка"));
            _predefinedOrganizations.Add(new Organization("Тернопільський національний технічний університет імені Івана Пулюя"));
            _predefinedOrganizations.Add(new Organization("Ужгородський національний університет"));
            _predefinedOrganizations.Add(new Organization("Українська академія банківської справи"));
            _predefinedOrganizations.Add(new Organization("Українська академія друкарства"));
            _predefinedOrganizations.Add(new Organization("Українська інженерно-педагогічна академія"));
            _predefinedOrganizations.Add(new Organization("Українська медична стоматологічна академія"));
            _predefinedOrganizations.Add(new Organization("Українське теріологічне товариство"));
            _predefinedOrganizations.Add(new Organization("Український гідрометеорологічний інститут"));
            _predefinedOrganizations.Add(new Organization("Український державний університет залізничного транспорту"));
            _predefinedOrganizations.Add(new Organization("Український державний хіміко-технологічний університет"));
            _predefinedOrganizations.Add(new Organization("Український інститут експертизи сортів рослин"));
            _predefinedOrganizations.Add(new Organization("Український мовно-інформаційний фонд"));
            _predefinedOrganizations.Add(new Organization("Український науково-дослідний інститут лісового господарства та агролісомеліорації ім.Г.М.Висоцького"));
            _predefinedOrganizations.Add(new Organization("Український науково-дослідний інститут олій та жирів"));
            _predefinedOrganizations.Add(new Organization("Уманський державний педагогічний університет імені Павла Тичини"));
            _predefinedOrganizations.Add(new Organization("Уманський національний університет садівництва"));
            _predefinedOrganizations.Add(new Organization("Університет банківської справи"));
            _predefinedOrganizations.Add(new Organization("Університет Державної фіскальної служби України"));
            _predefinedOrganizations.Add(new Organization("Університет економіки та права «Крок»"));
            _predefinedOrganizations.Add(new Organization("Університет менеджменту освіти"));
            _predefinedOrganizations.Add(new Organization("Університет митної справи та фінансів"));
            _predefinedOrganizations.Add(new Organization("Фізико-механічний інститут ім.Г.В.Карпенка"));
            _predefinedOrganizations.Add(new Organization("Фізико-технічний інститут низьких температур ім.Б.І.Вєркіна"));
            _predefinedOrganizations.Add(new Organization("Фізико-хімічний інститут ім.О.В.Богатського"));
            _predefinedOrganizations.Add(new Organization("Харківська державна академія дизайну і мистецтв"));
            _predefinedOrganizations.Add(new Organization("Харківська державна академія культури"));
            _predefinedOrganizations.Add(new Organization("Харківська державна академія фізичної культури"));
            _predefinedOrganizations.Add(new Organization("Харківська державна наукова бібліотека ім.В.Г.Короленка"));
            _predefinedOrganizations.Add(new Organization("Харківська медична академія післядипломної освіти"));
            _predefinedOrganizations.Add(new Organization("Харківський гуманітарний університет «Народна українська академія»"));
            _predefinedOrganizations.Add(new Organization("Харківський державний університет харчування та торгівлі"));
            _predefinedOrganizations.Add(new Organization("Харківський національний автомобільно-дорожній університет"));
            _predefinedOrganizations.Add(new Organization("Харківський національний аграрний університет ім.В.В.Докучаєва"));
            _predefinedOrganizations.Add(new Organization("Харківський національний економічний університет імені Семена Кузнеця"));
            _predefinedOrganizations.Add(new Organization("Харківський національний медичний університет"));
            _predefinedOrganizations.Add(new Organization("Харківський національний педагогічний університет імені Г.С.Сковороди"));
            _predefinedOrganizations.Add(new Organization("Харківський національний технічний університет сільського господарства імені Петра Василенка"));
            _predefinedOrganizations.Add(new Organization("Харківський національний університет будівництва та архітектури"));
            _predefinedOrganizations.Add(new Organization("Харківський національний університет внутрішніх справ"));
            _predefinedOrganizations.Add(new Organization("Харківський національний університет ім.В.Н.Каразіна"));
            _predefinedOrganizations.Add(new Organization("Харківський національний університет міського господарства ім.О.М.Бекетова"));
            _predefinedOrganizations.Add(new Organization("Харківський національний університет Повітряних Сил імені Івана Кожедуба"));
            _predefinedOrganizations.Add(new Organization("Харківський національний університет радіоелектроніки"));
            _predefinedOrganizations.Add(new Organization("Харківський регіональний інститут державного управління Національної академії державного управління при Президентові України"));
            _predefinedOrganizations.Add(new Organization("Харківський торговельно-економічний інститут КНТЕУ"));
            _predefinedOrganizations.Add(new Organization("Херсонська державна морська академія"));
            _predefinedOrganizations.Add(new Organization("Херсонський державний аграрний університет"));
            _predefinedOrganizations.Add(new Organization("Херсонський державний університет"));
            _predefinedOrganizations.Add(new Organization("Херсонський національний технічний університет"));
            _predefinedOrganizations.Add(new Organization("Херсонський політехнічний коледж Одеського національного політехнічного університету", new List<string>() { "Херсонский политехнический колледж ОНПУ" }));
            _predefinedOrganizations.Add(new Organization("Хмельницький національний університет"));
            _predefinedOrganizations.Add(new Organization("Центральноукраїнський державний педагогічний університет імені Володимира Винниченка"));
            _predefinedOrganizations.Add(new Organization("Черкаська дослідна станція біоресурсів"));
            _predefinedOrganizations.Add(new Organization("Черкаський державний бізнес-коледж"));
            _predefinedOrganizations.Add(new Organization("Черкаський державний технологічний університет"));
            _predefinedOrganizations.Add(new Organization("Черкаський національний університет імені Богдана Хмельницького"));
            _predefinedOrganizations.Add(new Organization("Чернівецький національний університет імені Юрія Федьковича"));
            _predefinedOrganizations.Add(new Organization("Чернівецький торговельно-економічний інститут КНТЕУ"));
            _predefinedOrganizations.Add(new Organization("Чернігівський національний педагогічний університет ім.Т.Г.Шевченка"));
            _predefinedOrganizations.Add(new Organization("Чернігівський національний технологічний університет"));
            _predefinedOrganizations.Add(new Organization("Чорноморський біосферний заповідник"));
            _predefinedOrganizations.Add(new Organization("Чорноморський національний університет імені Петра Могили"));
        }

        public static List<Organization> PredefinedOrganizations
        {
            get { return _predefinedOrganizations; }
        }

        public static List<string> GetAlternativeNames(string name)
        {
            var item = _predefinedOrganizations.FirstOrDefault(po => po.Name.Equals(name));
            if (item != null)
            {
                return item.AlternativeNames;
            }

            return new List<string>();
        }
    }
}
