// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ScienceActivityRecorder.Models;
using System;

namespace ScienceActivityRecorder.Migrations
{
    [DbContext(typeof(ProfileContext))]
    [Migration("20171111202058_DependenciesChange")]
    partial class DependenciesChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ScienceActivityRecorder.Models.AdditionalActivityInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastFillDate");

                    b.Property<string>("Num20VocationalGuidenceWork");

                    b.Property<string>("Num21ManagementOfCommonWork");

                    b.Property<string>("Num22CreationOfOffices");

                    b.Property<string>("Num23ParticipationInWorkOfBoards");

                    b.Property<string>("Num24NationalAward");

                    b.Property<int?>("ProfileId");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("AdditionalActivityInfo");
                });

            modelBuilder.Entity("ScienceActivityRecorder.Models.PersonalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AcademicDisciplines");

                    b.Property<string>("AdvancedTraining");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Degree");

                    b.Property<string>("EducationalInstitution");

                    b.Property<string>("FirstName");

                    b.Property<string>("HomeAddress");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Position");

                    b.Property<string>("Seniority");

                    b.HasKey("Id");

                    b.ToTable("PersonalInfo");
                });

            modelBuilder.Entity("ScienceActivityRecorder.Models.ProfessionalActivityInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastFillDate");

                    b.Property<string>("Num10OrganizationalWorkInEducationalInstitutions");

                    b.Property<string>("Num11ParticipationInValidationOfScientists");

                    b.Property<string>("Num12DegreeOfDoctor");

                    b.Property<string>("Num13PatentsAvailibility");

                    b.Property<string>("Num15DegreeOfDoctorOfPhilosophy");

                    b.Property<string>("Num16ManagementOfUkrainianOlympicWinnerStudent");

                    b.Property<string>("Num17OrganizingSocialActivities");

                    b.Property<string>("Num19CombinationOfTeachingAndPractice");

                    b.Property<string>("Num4ScientificManagement");

                    b.Property<string>("Num5ParticipationInInternationalProjects");

                    b.Property<string>("Num6LecturesInForeignLanguage");

                    b.Property<string>("Num7WorkInExpertBoard");

                    b.Property<string>("Num8ScientificGuidenceFunctions");

                    b.Property<string>("Num9MangementOfPriceWinnerStudent");

                    b.Property<int?>("ProfileId");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfessionalActivityInfo");
                });

            modelBuilder.Entity("ScienceActivityRecorder.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PersonalInfoId");

                    b.HasKey("Id");

                    b.HasIndex("PersonalInfoId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ScienceActivityRecorder.Models.PublicationActivityInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastFillDate");

                    b.Property<string>("Num14TeachingManualsAvailibility");

                    b.Property<string>("Num18PopularSciencePublicationsAvailibility");

                    b.Property<string>("Num1PublicationsInScienceMetricDatabases");

                    b.Property<string>("Num2PublicationsInUkrainianDatabases");

                    b.Property<string>("Num3TextbookAvailability");

                    b.Property<int?>("ProfileId");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PublicationActivityInfo");
                });

            modelBuilder.Entity("ScienceActivityRecorder.Models.AdditionalActivityInfo", b =>
                {
                    b.HasOne("ScienceActivityRecorder.Models.Profile")
                        .WithMany("AdditionalActivityInfo")
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("ScienceActivityRecorder.Models.ProfessionalActivityInfo", b =>
                {
                    b.HasOne("ScienceActivityRecorder.Models.Profile")
                        .WithMany("ProfessionalActivityInfo")
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("ScienceActivityRecorder.Models.Profile", b =>
                {
                    b.HasOne("ScienceActivityRecorder.Models.PersonalInfo", "PersonalInfo")
                        .WithMany()
                        .HasForeignKey("PersonalInfoId");
                });

            modelBuilder.Entity("ScienceActivityRecorder.Models.PublicationActivityInfo", b =>
                {
                    b.HasOne("ScienceActivityRecorder.Models.Profile")
                        .WithMany("PublicationActivityInfo")
                        .HasForeignKey("ProfileId");
                });
#pragma warning restore 612, 618
        }
    }
}
